server:
  port: 8001

spring:
  application:
    name: HaPayConfig
  cloud:
    config:
      server:
        native:
          search-locations: file:./config/center
  profiles:
     active: native

security:
  user:
    password: hengaiw

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

logging:
  file: ./logs/HaPayConfig.log

